### ISSUE TITLE
originalNames() and make.unique2

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#1]
The function originalNames calls formals(make.unique2), but I can't find the object make.unique2.  Is it necessary to include the call to formals?  Can you explain what is going on with formals(make.unique2)?

**Comment by syounkin** [comment]
Okay, I see the make.unique2 function definition in functions.R.

**Comment by rscharpf** [comment]
its definined in functions.R.

make.unique2 <- function(names, sep="___DUP") make.unique(names, sep)

the name-mangling ensures the names are unique and does this in a standard way such that the original names can be easily recovered.

**Comment by syounkin** [comment]
Got it.
