### ISSUE TITLE
setdiff method for GRangesList and GRanges

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#15]
I could really use a setdiff method that apples to a GRangesList and a GRanges.  It would return a list of the same length as GRangesList with each element i the GRanges object returned by setdiff(GRangesList[[i]], GRanges).

I will write a crude temporary fix that loops through the list, but I bet the IRanges folks have a better solution.

**Comment by syounkin** [comment]
How does one instantiate a GRangesList of length n, with zero-length GRanges as elements?

**Comment by syounkin** [comment]
Temporary fix is the method setdiff.sgy.

**Comment by rscharpf** [comment]
Hi Sam,

what about

gr <- setdiff(unlist(GRangesList), GRanges)
grl <- split(gr, values(gr)$factor)

(obviously, factor would have to be defined)

**Comment by syounkin** [comment]
Unfortunately, I believe metadata is lost with setdiff().  Because of that I don't think this will work so easily.  There has to be a slick way though.

**Comment by syounkin** [comment]
We no longer use setdiff, so it has been removed from the methods.
