### ISSUE TITLE
Drop .sgy suffix on setdiff.sgy and relist.sgy

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#18]
I gave these methods the .sgy suffix to avoid problems.  I would like to define methods to existing generics.  For instance I would like to define setdiff to act on GRangesList and Granges without masking generics, or otherwise introducing problems.  How does one create methods for existing generics?  What do I need to know about the existing generic and how do I access that?

**Comment by rscharpf** [comment]
importing the 'setdiff' method from GenomicRanges in your namespace,  imports both the generic and all defined methods for setdiff available in GenomicRanges.  So provided that you import the method, you can define setdiff methods using the generic.  The import directive would be something like

importMethodsFrom("GenomicRanges", setdiff)

If you do not want to use any of the setdiff methods in GEnomicRanges, then you would simply import the setdiff generic -- but I don't think that is what you want.  

If GenomicRanges were to define a method for GRangesList and GRanges, you should get a message when you load the package that a method is being masked.

**Comment by syounkin** [comment]
Thanks Rob.
setdiff is working now.

The relist generic is not similar enough to warrant using the same function, so I am going to rename the relist.sgy method.

**Comment by syounkin** [comment]
The relist.sgy method is now TrivialGRangesList.
