### ISSUE TITLE
Create CNVTrioExperiment Class

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#19]
Create this new class where everything is identical to SNPTrioExperiment, except the geno matrix should be renamed to avoid confusion, and the rowData are now non-trivial ranges.  Although the snpMatrix class would work for deletions, the name would be misleading.  Should we create a cnvMatrix, or start with a regular matrix?

With this class in hand we could introduce the deletionTDT, the denovo association, and so on.

MD could be constructed to map a SNPTrioExperiment (with logR and BAF in the array slot) to a CNVTrioExperiment.  Then, trioClasses could easily analyze the CNVTrioExperiment, alongside the original SNPTrioExperiment.

Any thoughts?

Thanks.

**Comment by rscharpf** [comment]
On Mar 8, 2013, at 3:03 PM, Samuel Younkin notifications@github.com wrote:

> Create this new class where everything is identical to SNPTrioExperiment, except the geno matrix should be renamed to avoid confusion, and the rowData are now non-trivial ranges. Although the snpMatrix class would work for deletions, the name would be misleading. Should we create a cnvMatrix, or start with a regular matrix?
> 
> With this class in hand we could introduce the deletionTDT, the denovo association, and so on.
> 
> MD could be constructed to map a SNPTrioExperiment (with logR and BAF in the array slot) to a CNVTrioExperiment. Then, trioClasses could easily analyze the CNVTrioExperiment, alongside the original SNPTrioExperiment.

Sounds good.  My only suggestion is to make a simple unit test for everything: class constructors, validity methods, coercision, tdt, etc.   For class constructors, define constructors with the same name of the above classes that 

(1) generates a valid empty instance by calling the constructor without arguments

checkTrue(validObject(SNPTrioSet())) 

checkTrue(validObject(Pedigree()))

etc.

(2) generates a valid instance from only assays (genotypes, ...) and pedigree:

validObject(SNPTrioSet(genotypes, pedigree))

If a new feature breaks an old feature, you will know automatically from the unit tests. 

Rob

**Comment by syounkin** [comment]
It would be more elegant if we had the following class structure:

SummarizedExperiment -> SNPExperiment
SummarizedExperiment -> CNVExperiment
SummarizedExperiment -> TrioExperiment

union(SNPExperiment, TrioExperiment) -> SNPTrioExperiment
union(CNVExperiment, TrioExperiment) -> CNVTrioExperiment

Being the first to define SNPExperiment and CNVExperiment as extensions of SummarizedExperiment could be awesome.
