### ISSUE TITLE
warning in data(ped) : data set 'ped' not found

### ISSUE THREAD

**Issue by rscharpf** [syounkin/Trioconductor#2]
data() error in trioClasses.Rnw (v0.0.3)

 I also commented the sourcing of the reload.R file.  You might want to put this in an eval=FALSE code chunk if this is for interactive debugging

**Comment by syounkin** [comment]
The data directory is not being pushed to github.  See .gitignore.  I wanted to be careful about posting data.  I can provide you with the data via enigma, if you like.

**Comment by syounkin** [comment]
See ~syounkin/public/trioClasses/ .

**Comment by rscharpf** [comment]
OK.  For the trioClasses vignette, we should substitute it with something that can be made public.
