### ISSUE TITLE
TrioSet with Gentoype in AssayData or TdtSet

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#5]
I propose we augment the TrioSet class to include genotype data, rather than introduce the TdtSet.

**Comment by rscharpf** [comment]
We don't require genotypes for our methods...

**Comment by syounkin** [comment]
I would like to eventually have lots of methods that use genotype data.  I think it would be best if the trio object contained all available data, and was general enough to handle both the case where there is no genotype data, and the case where there is only genotype data.  I think it is a mistake to add a new class for genotype only data.

**Comment by rscharpf** [comment]
I agree completely and, in fact, that is one of the objectives of the paper.  But that should be a specific class --  possibly inheriting from TrioSet.  When there is no genotype data, you have a TrioSet.  

Checking for whether genotypes are available before implementing a method defeats the purpose of using an S4 class.  If you try a genotype method on a TrioSet object it will fail automatically with a message like "method X is not defined for TrioSet". 

Rob

**Comment by syounkin** [comment]
I've gotten the ball rolling my defining gTrio and iTrio classes for genotype and intensity data, respectively.  See the vignette trioClasses on the collab branch.  I think it will be difficult to implement the one class approach that I prefer, so I want to begin like this.
