### ISSUE TITLE
Define Pedigree Class

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#9]
Define pedigree class as data frame or DataFrame with six vectors; pedid, id, fid, mid, sex, dx .

Are we happy with these names?

Should they be:
FAMID, ID, FID, MID, SEX, PHENO 
?

Sex (male = 1, female = 2)

~~

Coerce each vector to factor class.  My experience has shown that ids should always be factors, so that zero counts are possible in subset data.  This decision could likely cause difficulty for the user.

**Comment by rscharpf** [comment]
I vote for DataFrame.  No preference about the variable names.   Lower case might be easier to type.

**Comment by syounkin** [comment]
Defined class PedClass.  I don't like the name.  It's a slotless class that extends DataFrame.  No validity methods have been written yet, but the generator function does enforce the presence of the six fields; famid, id, fid, mid, sex, dx.

I have one complaint with DataFrame, and that is it doesn't work with with() unless explicit coercion to data.frame is performed first.  Seems like an easy fix for the IRanges guys.
